name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.0'
      - name: Install pnpm and caprover
        run: npm install -g pnpm caprover
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: "Version"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git remote set-url origin "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git reset --hard

          pnpm lerna version --conventional-commits --yes

          cd packages/bot
          pnpm run genversion

          git add .
          git commit -m "chore: update version.ts [skip ci]"
          git push

      - name: Deploy
        run: caprover deploy -h ${{ secrets.CAPROVER_SERVER_PROD }} -p ${{ secrets.CAPROVER_PASSWORD_PROD }} -a bot -b main